In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer

# Convert data to pandas DataFrame

In [3]:
l = ['010011','110111','101110','011101','011101','001101','?11?0?','?11?2?']

In [28]:
l_fit = ['010011','110111','101110','011101','011101','001101']
l_test = ['?11?0?','?11?2?']

In [31]:
l_fit_x = ''
l_fit_y = ''
for i in range(0,len(l_fit),2):
    l_fit_x += l_fit[i]
    l_fit_y += l_fit[i+1]

In [32]:
print('x: ',l_fit_x,' y: ',l_fit_y)

x:  010011101110011101  y:  110111011101001101


In [33]:
l_fit_feed = [[int(i), int(j)] for i,j in zip(l_fit_x,l_fit_y) ]

In [34]:
l_fit_feed

[[0, 1],
 [1, 1],
 [0, 0],
 [0, 1],
 [1, 1],
 [1, 1],
 [1, 0],
 [0, 1],
 [1, 1],
 [1, 1],
 [1, 0],
 [0, 1],
 [0, 0],
 [1, 0],
 [1, 1],
 [1, 1],
 [0, 0],
 [1, 1]]

In [35]:
imp = IterativeImputer(max_iter=10,random_state=0)

In [36]:
imp.fit(l_fit_feed)

IterativeImputer(random_state=0)

In [38]:
np.round(imp.transform([[0,np.nan]]))

array([[0., 1.]])

In [5]:
s = pd.Series(l)

In [6]:
s

0    010011
1    110111
2    101110
3    011101
4    011101
5    001101
6    ?11?0?
7    ?11?2?
dtype: object

In [7]:
df = s.str.split(pat='',n=6, expand=True)
df

0  1  2  3  4  5  6
0    0  1  0  0  1  1
1    1  1  0  1  1  1
2    1  0  1  1  1  0
3    0  1  1  1  0  1
4    0  1  1  1  0  1
5    0  0  1  1  0  1
6    ?  1  1  ?  0  ?
7    ?  1  1  ?  2  ?

In [8]:
df = df.replace({'?': np.nan})
df

0    1  2  3    4  5    6
0      0  1  0    0  1    1
1      1  1  0    1  1    1
2      1  0  1    1  1    0
3      0  1  1    1  0    1
4      0  1  1    1  0    1
5      0  0  1    1  0    1
6    NaN  1  1  NaN  0  NaN
7    NaN  1  1  NaN  2  NaN

In [9]:
df = df.drop(columns=[0])
df

1  2  3    4  5    6
0    0  1  0    0  1    1
1    1  1  0    1  1    1
2    1  0  1    1  1    0
3    0  1  1    1  0    1
4    0  1  1    1  0    1
5    0  0  1    1  0    1
6  NaN  1  1  NaN  0  NaN
7  NaN  1  1  NaN  2  NaN

In [10]:
df2 = df.astype(int, errors='ignore', copy=True)
df2

1  2  3    4  5    6
0    0  1  0    0  1    1
1    1  1  0    1  1    1
2    1  0  1    1  1    0
3    0  1  1    1  0    1
4    0  1  1    1  0    1
5    0  0  1    1  0    1
6  NaN  1  1  NaN  0  NaN
7  NaN  1  1  NaN  2  NaN

In [11]:
df3 = df2.transpose()
df3

0  1  2  3  4  5    6    7
1  0  1  1  0  0  0  NaN  NaN
2  1  1  0  1  1  0    1    1
3  0  0  1  1  1  1    1    1
4  0  1  1  1  1  1  NaN  NaN
5  1  1  1  0  0  0    0    2
6  1  1  0  1  1  1  NaN  NaN

In [12]:
df4 = df2.copy(deep=True)

In [13]:
df4.loc[6.5] = [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan]
df4.loc[7.5] = [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan]

In [14]:
df4 = df4.sort_index().reset_index(drop=True)
df4

1    2    3    4    5    6
0    0    1    0    0    1    1
1    1    1    0    1    1    1
2    1    0    1    1    1    0
3    0    1    1    1    0    1
4    0    1    1    1    0    1
5    0    0    1    1    0    1
6  NaN    1    1  NaN    0  NaN
7  NaN  NaN  NaN  NaN  NaN  NaN
8  NaN    1    1  NaN    2  NaN
9  NaN  NaN  NaN  NaN  NaN  NaN

In [47]:
df4.loc[7] = [np.nan,0,0,np.nan,0,np.nan]
df4.loc[8] = [np.nan,1,1,np.nan,1,np.nan]
df4.loc[9] = [np.nan,0,0,np.nan,1,np.nan]
df4

1  2  3    4  5    6
0    0  1  0    0  1    1
1    1  1  0    1  1    1
2    1  0  1    1  1    0
3    0  1  1    1  0    1
4    0  1  1    1  0    1
5    0  0  1    1  0    1
6  NaN  1  1  NaN  0  NaN
7  NaN  0  0  NaN  0  NaN
8  NaN  1  1  NaN  1  NaN
9  NaN  0  0  NaN  1  NaN

In [52]:
imp = IterativeImputer(max_iter=10,random_state=0)
np.round(imp.fit_transform(df4))

array([[ 0.,  1.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  1.,  1.,  1.],
       [ 1.,  0.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  0.,  1.],
       [ 0.,  1.,  1.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  0.,  1.],
       [-0.,  1.,  1.,  1.,  0.,  1.],
       [-0.,  0.,  0.,  1.,  0.,  2.],
       [ 1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  0.,  0.,  1.,  1.,  1.]])

In [16]:
# select col4
df4[2]

0      1
1      1
2      0
3      1
4      1
5      0
6      1
7    NaN
8      1
9    NaN
Name: 2, dtype: object

In [17]:
l2_fit = [[1,1],[0,1],[1,0]]
l2_test = [[1,np.nan],[1,np.nan]]

In [43]:
l3_fit = [df4.loc[0]]
#,df4.loc[1],[df4.loc[2],df4.loc[3]],df4.loc[4],df.loc[5]

In [40]:
l3_test = [df4.loc[6],df4.loc[7]]

In [41]:
imp = IterativeImputer(max_iter=10,random_state=0)

In [44]:
imp.fit(l3_fit)

IterativeImputer(random_state=0)

In [45]:
np.round(imp.transform(l3_test))

array([[0., 1., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 1.]])

# Imputation with Scikit-Learn

## nearest neighbors imputation: not working

In [39]:
# weights is uniform or distance
imputer = KNNImputer(n_neighbors=2, weights='distance')

In [41]:
imputer.fit_transform(df2)

array([[0. , 1. , 0. , 0. , 1. , 1. ],
       [1. , 1. , 0. , 1. , 1. , 1. ],
       [1. , 0. , 1. , 1. , 1. , 0. ],
       [0. , 1. , 1. , 1. , 0. , 1. ],
       [0. , 1. , 1. , 1. , 0. , 1. ],
       [0. , 0. , 1. , 1. , 0. , 1. ],
       [0. , 1. , 1. , 1. , 0. , 1. ],
       [0.5, 1. , 1. , 0.5, 2. , 1. ]])

## Univariate imputation: mean, median or most_frequent not working

In [48]:
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

In [52]:
imp.fit_transform(df2)

array([['0', '1', '0', '0', '1', '1'],
       ['1', '1', '0', '1', '1', '1'],
       ['1', '0', '1', '1', '1', '0'],
       ['0', '1', '1', '1', '0', '1'],
       ['0', '1', '1', '1', '0', '1'],
       ['0', '0', '1', '1', '0', '1'],
       ['0', '1', '1', '1', '0', '1'],
       ['0', '1', '1', '1', '2', '1']], dtype=object)

## Multivariate imputation

In [53]:
imp = IterativeImputer(max_iter=10, random_state=0)

In [64]:
imp.fit_transform(df4)

array([[ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         1.        ],
       [ 1.        ,  1.        ,  0.        ,  1.        ,  1.        ,
         1.        ],
       [ 1.        ,  0.        ,  1.        ,  1.        ,  1.        ,
         0.        ],
       [ 0.        ,  1.        ,  1.        ,  1.        ,  0.        ,
         1.        ],
       [ 0.        ,  1.        ,  1.        ,  1.        ,  0.        ,
         1.        ],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  0.        ,
         1.        ],
       [-0.16664873,  1.        ,  1.        ,  0.8333444 ,  0.        ,
         0.99999958],
       [ 0.45832332,  0.75      ,  0.75      ,  0.8333355 ,  0.625     ,
         0.62500653],
       [ 1.83323526,  1.        ,  1.        ,  0.8333396 ,  2.        ,
        -0.99994735],
       [ 0.45832332,  0.75      ,  0.75      ,  0.8333355 ,  0.625     ,
         0.62500653]])